"""What the converter's internal representation is today.

Issue #2 asks to verify first: how does the converter represent the workflow
internally, and is any intermediate artifact serialised to disk? These tests
record the answers before anything is changed, so the change can be measured
against them rather than described.

The short answers: four plain dataclasses, no version marker on any of them,
nothing written to disk but the Snakefile -- and the representation could not
be written to disk even if something wanted to, because IOMode is not JSON
serialisable.
"""

import dataclasses
import json

import pytest

import convert
from tests.fixtures.tools import BUNDLES


@pytest.fixture(autouse=True)
def stub_registry(monkeypatch):
    monkeypatch.setattr(
        convert, "fetch_tool", lambda tool_id, repo: BUNDLES[tool_id.split("-")[0]]
    )


def a_workflow():
    return convert.parse_biochef_workflow(
        {
            "nodes": [
                {"id": "input-1", "type": "inputWorkflowNode",
                 "data": {"outputs": {"out": {"kind": "text", "data": "x"}}}},
                {"id": "tn93.distance-1", "type": "workflowNode",
                 "data": {"label": "t", "repo": "r", "paramValues": {}, "outputs": {}}},
                {"id": "output-1", "type": "outputWorkflowNode", "data": {}},
            ],
            "edges": [
                {"source": "input-1", "sourceHandle": "out",
                 "target": "tn93.distance-1", "targetHandle": "in"},
                {"source": "tn93.distance-1", "sourceHandle": "out",
                 "target": "output-1", "targetHandle": "in"},
            ],
        }
    )


def test_the_representation_is_four_plain_dataclasses():
    for cls in (convert.Workflow, convert.Node, convert.IO, convert.Param):
        assert dataclasses.is_dataclass(cls), f"{cls.__name__} is not a dataclass"

    assert [f.name for f in dataclasses.fields(convert.Workflow)] == ["nodes"]
    assert [f.name for f in dataclasses.fields(convert.Node)] == [
        "id", "bin", "inputs", "outputs", "parameters",
    ]
    assert [f.name for f in dataclasses.fields(convert.IO)] == [
        "file", "mode", "hardcoded_file", "flag",
    ]
    assert [f.name for f in dataclasses.fields(convert.Param)] == [
        "name", "value", "flag",
    ]


def test_nothing_carries_a_version():
    """No field on any of the four says which shape this is.

    So a Snakefile generated by one revision of the converter is
    indistinguishable from one generated by another, and an artifact written by
    an older Agent could not be recognised as older.
    """
    for cls in (convert.Workflow, convert.Node, convert.IO, convert.Param):
        names = [f.name.lower() for f in dataclasses.fields(cls)]
        assert not any("version" in n for n in names), cls.__name__


def test_the_representation_cannot_be_serialised_to_json():
    """This is the finding that matters.

    Writing an intermediate artifact is not merely absent, it is not currently
    possible: IOMode is an Enum, and asdict keeps enum members as-is.
    """
    workflow = a_workflow()

    with pytest.raises(TypeError, match="IOMode is not JSON serializable"):
        json.dumps(dataclasses.asdict(workflow))


def test_no_validation_happens_on_the_way_in():
    """parse_biochef_workflow trusts the editor export completely.

    A node missing "data" raises KeyError from deep inside the parse rather than
    being reported as an invalid document, which is what a schema would give.
    """
    with pytest.raises(KeyError):
        convert.parse_biochef_workflow(
            {"nodes": [{"id": "tn93.distance-1", "type": "workflowNode"}], "edges": []}
        )
